language: java
jdk:
  - openjdk17
services:
  - docker

before_install:
  - chmod +x gradlew
  - openssl aes-256-cbc -K $encrypted_646acf6fed41_key -iv $encrypted_646acf6fed41_iv -in scripts/pricetaglist.pem.enc -out scripts/pricetaglist.pem -d
  - chmod 600 scripts/deploy_key.pem

cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"

script:
  - "./gradlew clean build"

after_success:
  - docker build -t yi5oyu/pricetaglist .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push yi5oyu/pricetaglist

notifications:
  email:
    recipients:
      - pricetaglist.gmail.com

before_deploy:
  - git reset --hard

deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: master