language: java
jdk:
  - openjdk17

services:
  - docker

before_install:
  - chmod +x gradlew
  - chmod +x scripts/deploy.sh

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
  - ./gradlew build

after_success:
  - docker build -t yi5oyu/pricetaglist .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push yi5oyu/pricetaglist

notifications:
  email:
    recipients:
      - pricetaglist.gmail.com

deploy:
  provider: script
  script: |
    git config --global user.email "yi5oyu@gmail.com"
    git config --global user.name "yi5oyu"
    git add gradlew scripts/deploy.sh
    git commit -m "Prepare for deployment"
    git checkout main
    bash scripts/deploy.sh
  on:
    branch: main