language: java
jdk:
- openjdk17
services:
- docker
before_install:
  - chmod +x gradlew

cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
script:
- "./gradlew clean build"
after_success:
- docker build -t yi5oyu/pricetaglist .
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push yi5oyu/pricetaglist
notifications:
  email:
    recipients:
    - pricetaglist.gmail.com

before_deploy:
- git reset --hard
deploy:
  provider: script
  script: bash scripts/mk.sh
  on:
    branch: master
