language: java
jdk:
  - openjdk17

services:
  - docker

before_install:
  - chmod +x gradlew
  - echo "ENCRYPTED_PASSWORD: $ENCRYPTED_PASSWORD"
  - openssl aes-256-cbc -d -pbkdf2 -k "$ENCRYPTED_PASSWORD" -in scripts/pricetaglist.pem.enc -out scripts/deploy_key.pem
  - chmod 600 scripts/deploy_key.pem

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
  - ./gradlew clean build

after_success:
  - docker build -t yi5oyu/pricetaglist .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push yi5oyu/pricetaglist

notifications:
  email:
    recipients:
      - pricetaglist.gmail.com

deploy:
  provider: script
  script:
    bash scripts/deploy.sh
  on:
    branch: master