language: java
jdk:
- openjdk17
services:
- docker
before_install:
<<<<<<< Updated upstream
  - chmod +x gradlew

=======
- openssl aes-256-cbc -K $encrypted_646acf6fed41_key -iv $encrypted_646acf6fed41_iv
  -in pricetaglist.pem.enc -out ~\/Desktop/pem/pricetaglist.pem -d
- chmod +x gradlew
- openssl aes-256-cbc -d -pbkdf2 -k "$ENCRYPTED_PASSWORD" -in scripts/pricetaglist.pem.enc
  -out scripts/deploy_key.pem
- chmod 600 scripts/deploy_key.pem
>>>>>>> Stashed changes
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
script:
- "./gradlew clean build"
after_success:
- docker build -t yi5oyu/pricetaglist .
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push yi5oyu/pricetaglist
notifications:
  email:
    recipients:
<<<<<<< Updated upstream
      - pricetaglist.gmail.com

before_deploy:
  - git reset --hard

deploy:
  provider: script
  script:
    bash scripts/test.sh
#    bash scripts/deploy.sh
=======
    - pricetaglist.gmail.com
deploy:
  provider: script
  script: bash scripts/deploy.sh
>>>>>>> Stashed changes
  on:
    branch: master
