language: java
jdk:
- openjdk17
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_<new_key> -iv $encrypted_<new_iv> -in scripts/pricetaglist.pem.enc -out scripts/pricetaglist.pem -d
- chmod +x gradlew
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
script:
- "./gradlew clean build"
after_success:
- docker build -t yi5oyu/pricetaglist .
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push yi5oyu/pricetaglist
notifications:
  email:
    recipients:
    - pricetaglist.gmail.com
before_deploy:
- git reset --hard
deploy:
  provider: script
  script: bash scripts/test.sh
  on:
    branch: master
