# ?? ??
server:
  port: 8080
spring:
  thymeleaf:
    cache: false
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

## real1 ???? ??
#---
#spring:
#  config:
#    activate:
#      on-profile: springboot1
#server:
#  port: 8080
#
## real2 ???? ??
#---
#spring:
#  config:
#    activate:
#      on-profile: springboot2
#server:
#  port: 8081