server:
  port: ${PORT:8888}
  tomcat:
    connection-timeout: 5h
spring:
  jackson:
    time-zone: Asia/Seoul
  thymeleaf:
    cache: false
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect