# ?? ??
server:
  port: 8889
  tomcat:
    connection-timeout: 5h
spring:
  jackson:
    time-zone: Asia/Seoul
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://pricetaglist.c16ouquk62gs.ap-northeast-2.rds.amazonaws.com:3306/products
    username: yi5oyu
    password: dud500253!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

## real1 ???? ??
#---
#spring:
#  config:
#    activate:
#      on-profile: springboot1
#server:
#  port: 8080
#
## real2 ???? ??
#---
#spring:
#  config:
#    activate:
#      on-profile: springboot2
#server:
#  port: 8081